#!/bin/bash

## hyphop ##

#? speech2text simple script wrapper for open-ai whisper - voice recognition speech to text

P=/tmp/s2t.pid

hops(){
    pkill --signal INT arecord
    echo "BYBY"
#    echo "Speech to Text $(cat $P 2>/dev/null)"
}

CMD(){
    echo "# $@">&2
    "$@"
}

DIE(){
    echo "[DIE] $@">&2
    exit 1
}

#MODEL=${MODE:-turbo} # big and much slow
MODEL=${MODE:-small}
DURATION=${DURATION:-30}
CACHE=~/.cache/whisper
WA=~/whisper-env/bin/activate
WORK=${WORK:-~/speech2text}

[ -s $WA ] && source $WA

whisper=${whisper:-$(which whisper 2>/dev/null)}

[ -s "$whisper" ] || DIE "whisper not found, need to install...

    sudo apt install python3 python3-pip
    sudo apt install python3.12-venv
    sudo apt install git
    python3 -m venv ~/whisper-env
    source ~/whisper-env/bin/activate
    cd
    pip install git+https://github.com/openai/whisper.git

"

[ -s "$CACHE/$MODEL.pt" ] || {

echo Download model: $MODEL to $CACHE ...
#whisper --model "$MODEL" --help

cat <<EOF | python3
import whisper

# Load the "small" model (downloads if not available)
model = whisper.load_model("$MODEL")
print("Model downloaded successfully!")

EOF
}

which arecord 2>/dev/null || DIE "arecord not found, need to install...

    sudo apt install alsa-utils

"

trap hops INT TERM KILL


mkdir -p "$WORK"
cd "$WORK"

F="$WORK/s2t.$(hostname)-$(date +%s)".wav
LOG=${LOG:-/tmp/speech2text.log}

echo "Speech to Text > $F ... Ctrl+C to stop"
echo Listening microphone $DURATION sec ...

CMD arecord \
    --vumeter=mono \
    --process-id-file "$P" \
    -d $DURATION \
    -f S16_LE \
    -c1 \
    -r16000 "$F"

[ -s "$F" ] || DIE

TXT=${F%.*}.txt

echo "Speech to Text > $F > $TXT"
CMD whisper "$F" --model $MODEL "$@" #2>$LOG

grep "" -H "$TXT"

which xsel >/dev/null 2>&2 || DIE "sudo apt install xsel
? if auto copy into clipboard buffer needed ?
"

xsel -b < "$TXT"

exit

<<END

Detected language: English
[00:00.000 --> 00:05.000]  Hello, I love you. What is your name?
/home/hyp/speech2text/s2t.hop-1733884614.txt:Hello, I love you. What is your name?
